// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKW0bwth_Vd0byzLnXSfW4ahUnuiVZons',
    appId: '1:1082416948293:web:c0ccc2bbf7b7f097716f2c',
    messagingSenderId: '1082416948293',
    projectId: 'insight-talk',
    authDomain: 'insight-talk.firebaseapp.com',
    storageBucket: 'insight-talk.appspot.com',
    measurementId: 'G-TP2W2W9FZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvagBuCzwnYxuuS_DS0vo7XizR-mCVLlk',
    appId: '1:1082416948293:android:473187454e368941716f2c',
    messagingSenderId: '1082416948293',
    projectId: 'insight-talk',
    storageBucket: 'insight-talk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6lj7wbv6I_r7vxHdZGKtFXr7gsZEmZFQ',
    appId: '1:1082416948293:ios:1430c53e6fbb5a01716f2c',
    messagingSenderId: '1082416948293',
    projectId: 'insight-talk',
    storageBucket: 'insight-talk.appspot.com',
    iosBundleId: 'com.example.insighttalkFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6lj7wbv6I_r7vxHdZGKtFXr7gsZEmZFQ',
    appId: '1:1082416948293:ios:1430c53e6fbb5a01716f2c',
    messagingSenderId: '1082416948293',
    projectId: 'insight-talk',
    storageBucket: 'insight-talk.appspot.com',
    iosBundleId: 'com.example.insighttalkFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKW0bwth_Vd0byzLnXSfW4ahUnuiVZons',
    appId: '1:1082416948293:web:dde4ebad5b7ae798716f2c',
    messagingSenderId: '1082416948293',
    projectId: 'insight-talk',
    authDomain: 'insight-talk.firebaseapp.com',
    storageBucket: 'insight-talk.appspot.com',
    measurementId: 'G-03640FY4Q1',
  );
}
