// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLlbvurUf2ZRB8S81l4tuw_IOegTOczks',
    appId: '1:6667383254:web:19d55b2048bd51340b3477',
    messagingSenderId: '6667383254',
    projectId: 'insight-talk-af3e1',
    authDomain: 'insight-talk-af3e1.firebaseapp.com',
    storageBucket: 'insight-talk-af3e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH5V-8PrNFiQ8iwDEZhieadIwP1DSfU8E',
    appId: '1:6667383254:android:552c8ca4a3cc2ac80b3477',
    messagingSenderId: '6667383254',
    projectId: 'insight-talk-af3e1',
    storageBucket: 'insight-talk-af3e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Gl-o3nuyXhOH48Uws09VgTY6zIYKWSE',
    appId: '1:6667383254:ios:4e8a79c8817f9a340b3477',
    messagingSenderId: '6667383254',
    projectId: 'insight-talk-af3e1',
    storageBucket: 'insight-talk-af3e1.appspot.com',
    iosClientId: '6667383254-q3908phkt9q8ab4ijjcuu88s4qmml1i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.insighttalkExpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Gl-o3nuyXhOH48Uws09VgTY6zIYKWSE',
    appId: '1:6667383254:ios:4e8a79c8817f9a340b3477',
    messagingSenderId: '6667383254',
    projectId: 'insight-talk-af3e1',
    storageBucket: 'insight-talk-af3e1.appspot.com',
    iosClientId: '6667383254-q3908phkt9q8ab4ijjcuu88s4qmml1i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.insighttalkExpert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLlbvurUf2ZRB8S81l4tuw_IOegTOczks',
    appId: '1:6667383254:web:b8ed9e38407387aa0b3477',
    messagingSenderId: '6667383254',
    projectId: 'insight-talk-af3e1',
    authDomain: 'insight-talk-af3e1.firebaseapp.com',
    storageBucket: 'insight-talk-af3e1.appspot.com',
  );
}
